[package]
name = "tipme"
version = "0.1.0"
authors = ["robertdurst <rsdurst@colby.edu>"]
license = "MIT"
build = "build.rs"

[lib]
name = "tipme"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.1.22"

[dependencies]
neon = "0.1.22"
reqwest = "0.8.5"
ws = "*"
