[package]
name = "tipme"
version = "0.1.0"
authors = ["robertdurst <rsdurst@colby.edu>"]
license = "MIT"

[lib]
name = "tipme"

[dependencies]
reqwest = "0.8.5"
ws = "*"
serde_json = "1.0"
stellar-client = "0.1.1"
futures-timer = "0.1"
futures = "*"
postgres = "0.15"

